spring:
  devtools:
    livereload:
      enabled: true  #禁用livereload服务器
    remote:
      restart:
        enabled: false
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  mvc:
    favicon:
      enabled: false #禁用浏览器图标
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  max-http-header-size: 104800 #配置请求头内容大小
feign:
  client:
    config:
      default: #服务名，填写default为所有服务1
        connectTimeout: 1000
        readTimeout: 600000
#debug: true #调试模式，将会看到更多的日志信息。默认关闭
##===设置服务熔断超时
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 600000